-- ============================================================================
-- admin-delete.sql — make "Radera" actually work for admin.
--
-- Run by hand in the Supabase SQL editor. Not part of the Vite build.
-- Safe to re-run in full: every step skips work that is already done.
--
-- ---------------------------------------------------------------------------
-- THE PROBLEM THIS SOLVES
--
-- <DeleteButton> has existed on all five detail pages (fastighet, lägenhet,
-- felanmälan, besiktning, projekt) for a while, and it already renders only
-- for admin. It nonetheless failed in practice for two independent reasons:
--
--   1. FOREIGN KEYS. Child rows were created with the PostgREST default
--      (NO ACTION), so deleting a fastighet that still has lägenheter,
--      ärenden, dokument or loggbok rows raises 23503 and the button shows
--      "Kan inte raderas — det finns kopplad data kvar". A building with any
--      history at all could therefore never be deleted.
--
--   2. RLS. Several tables have row level security on with SELECT/INSERT/
--      UPDATE policies but no DELETE policy. Postgres denies what no policy
--      permits, so `.delete()` returned 0 rows and the UI reported success
--      while nothing was removed — the worst of the two failure modes.
--
-- Step 2 fixes the first, step 3 the second.
--
-- ---------------------------------------------------------------------------
-- PRODUCT DECISION ENCODED HERE (client, 2026-07-27): CASCADE.
--
-- Deleting a fastighet deletes everything under it — lägenheter, felanmälningar,
-- besiktningar, projekt, objekt, dokument, loggbok, åtgärder. Deleting a
-- lägenhet deletes its ärenden and loggbok. This is not recoverable from the
-- UI; the confirm dialog in DeleteButton.tsx names the counts before it runs.
--
-- audit_events is deliberately NOT part of any cascade — it has no foreign
-- keys at all (see the header of audit-events.sql: "an audit trail must
-- outlive the thing it describes"), so a cascade leaves the Historik intact.
-- Admins clear Historik explicitly instead, via the multi-select toolbar —
-- see step 3's note on audit_events.
-- ============================================================================


-- ---------------------------------------------------------------------------
-- 1. PREFLIGHT — READ-ONLY. Run this first and read the output.
--    is_admin() is created by hand in the dashboard and has no DDL in this
--    repo. Nothing below works without it. Expect has_is_admin = true.
-- ---------------------------------------------------------------------------
SELECT
  EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'is_admin') AS has_is_admin;

-- What the cascade will actually remove, before you remove it. Fill in an id
-- to preview a specific building.
--   SELECT
--     (SELECT count(*) FROM apartments      WHERE property_id = '<id>') AS lagenheter,
--     (SELECT count(*) FROM issues          WHERE property_id = '<id>') AS felanmalningar,
--     (SELECT count(*) FROM inspections     WHERE property_id = '<id>') AS besiktningar,
--     (SELECT count(*) FROM projects        WHERE property_id = '<id>') AS projekt,
--     (SELECT count(*) FROM logbook_entries WHERE property_id = '<id>') AS loggbok,
--     (SELECT count(*) FROM documents       WHERE property_id = '<id>') AS dokument;


-- ---------------------------------------------------------------------------
-- 2. Foreign keys → ON DELETE CASCADE.
--
--    Done as a sweep rather than a list of hand-written ALTERs because the
--    schema was generated by Lovable and the constraint names are not
--    predictable. The sweep finds every single-column FK pointing at one of
--    the parent tables and rewrites it in place, keeping the existing name.
--
--    It is a no-op for any constraint that already has the right action, so
--    re-running this file costs nothing.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  -- Deleting one of these must not be blocked by anything below it.
  parents CONSTANT TEXT[] := ARRAY[
    'properties', 'apartments', 'issues', 'inspections', 'projects',
    'property_objects', 'logbook_entries'
  ];

  -- Exceptions: child.column pairs where the child OUTLIVES the parent and
  -- only loses the link. Everything not listed here cascades.
  --   contacts.property_id          — an entreprenör is not owned by a building;
  --                                   they may be ansvarig in several. Also,
  --                                   deleting the contact row would break
  --                                   issues.assigned_contact_id elsewhere.
  --   property_objects.apartment_id — a hiss/tvättstuga belongs to the
  --                                   building; the apartment link is optional
  --                                   (see the objekt notes in CLAUDE.md).
  --   *.property_object_id          — an ärende or loggbok row describing an
  --                                   objekt is still a real record once the
  --                                   objekt is gone.
  set_null CONSTANT TEXT[] := ARRAY[
    'contacts.property_id',
    'property_objects.apartment_id',
    'issues.property_object_id',
    'inspections.property_object_id',
    'logbook_entries.property_object_id'
  ];

  r         RECORD;
  v_action  TEXT;
  v_current TEXT;
  v_notnull BOOLEAN;
  v_changed INT := 0;
BEGIN
  FOR r IN
    SELECT con.oid         AS conoid,
           con.conname     AS conname,
           con.confdeltype AS confdeltype,
           src.relname     AS child_table,
           att.attname     AS child_column,
           att.attnotnull  AS child_notnull,
           tgt.relname     AS parent_table
    FROM pg_constraint con
    JOIN pg_class     src ON src.oid = con.conrelid
    JOIN pg_class     tgt ON tgt.oid = con.confrelid
    JOIN pg_namespace ns  ON ns.oid  = src.relnamespace
    JOIN pg_attribute att ON att.attrelid = con.conrelid
                         AND att.attnum   = con.conkey[1]
    WHERE con.contype = 'f'
      AND ns.nspname  = 'public'
      AND tgt.relname = ANY (parents)
      AND array_length(con.conkey, 1) = 1     -- composite FKs: none exist, and
                                              -- rewriting one blind is unsafe
    ORDER BY src.relname, att.attname
  LOOP
    v_notnull := r.child_notnull;

    IF (r.child_table || '.' || r.child_column) = ANY (set_null) THEN
      -- SET NULL on a NOT NULL column raises at delete time, not now, so the
      -- failure would surface as a mystery 23502 much later. Fall back.
      v_action := CASE WHEN v_notnull THEN 'CASCADE' ELSE 'SET NULL' END;
      IF v_notnull THEN
        RAISE NOTICE '%.% is NOT NULL — cascading instead of SET NULL',
          r.child_table, r.child_column;
      END IF;
    ELSE
      v_action := 'CASCADE';
    END IF;

    v_current := CASE r.confdeltype
                   WHEN 'c' THEN 'CASCADE'
                   WHEN 'n' THEN 'SET NULL'
                   WHEN 'd' THEN 'SET DEFAULT'
                   WHEN 'r' THEN 'RESTRICT'
                   ELSE 'NO ACTION'
                 END;

    CONTINUE WHEN v_current = v_action;

    EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT %I',
                   r.child_table, r.conname);
    EXECUTE format(
      'ALTER TABLE public.%I ADD CONSTRAINT %I FOREIGN KEY (%I) '
      'REFERENCES public.%I(id) ON DELETE %s',
      r.child_table, r.conname, r.child_column, r.parent_table, v_action);

    v_changed := v_changed + 1;
    RAISE NOTICE '% (%.% -> %): % -> %',
      r.conname, r.child_table, r.child_column, r.parent_table,
      v_current, v_action;
  END LOOP;

  RAISE NOTICE '% foreign key(s) rewritten.', v_changed;
END $$;


-- ---------------------------------------------------------------------------
-- 3. Admin DELETE policies.
--
--    Two rules, both load-bearing:
--
--    a) RLS is NEVER enabled here. A table with RLS off today is protected by
--       grants alone; switching it on while adding only a DELETE policy would
--       deny SELECT/INSERT/UPDATE to everyone and take the app down. The loop
--       therefore adds a policy only where RLS is already on, and otherwise
--       just makes sure the DELETE grant exists.
--
--    b) The policy is `is_admin()` and nothing else. Styrelse is read-only by
--       spec and an entreprenör must never be able to erase an ärende they
--       were assigned. Deletion is admin-only everywhere in this app, which is
--       also what <DeleteButton> and the loggbok toolbar assume client-side —
--       keep the two in agreement.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  tables CONSTANT TEXT[] := ARRAY[
    -- the five the client asked for
    'properties', 'apartments', 'issues', 'inspections', 'projects',
    -- loggbok
    'logbook_entries', 'logbook_comments',
    -- children reachable through a cascade, and deletable in their own right
    'property_objects', 'documents', 'property_history', 'actions',
    'issue_images', 'project_images', 'issue_comments', 'issue_status_history',
    'protocols', 'inspection_protocols', 'budget_items', 'property_budgets',
    -- Historik. See the note below — this reverses an earlier decision.
    'audit_events'
  ];
  t       TEXT;
  v_rls   BOOLEAN;
  v_pol   TEXT;
BEGIN
  FOREACH t IN ARRAY tables LOOP
    SELECT c.relrowsecurity INTO v_rls
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relname = t AND c.relkind = 'r';

    IF NOT FOUND THEN
      RAISE NOTICE 'skip % — no such table', t;
      CONTINUE;
    END IF;

    EXECUTE format('GRANT DELETE ON public.%I TO authenticated', t);

    IF NOT v_rls THEN
      RAISE NOTICE '% — RLS off, grant only (deliberately not enabling RLS)', t;
      CONTINUE;
    END IF;

    v_pol := t || '_delete_admin';
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', v_pol, t);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR DELETE TO authenticated USING (is_admin())',
      v_pol, t);
    RAISE NOTICE '% — policy % created', t, v_pol;
  END LOOP;
END $$;

-- audit_events: this is a deliberate reversal, recorded so the next reader
-- does not "fix" it back.
--
-- audit-events.sql argues an audit log an admin can edit is not an audit log,
-- and revoked INSERT/UPDATE/DELETE from `authenticated` accordingly. The client
-- overrode that on 2026-07-27: admin must be able to clear Historik, selected
-- rows or all of it, leaving no tombstone.
--
-- What is preserved: INSERT and UPDATE stay revoked. A row still cannot be
-- fabricated or rewritten from the client — only removed. So an entry that
-- exists is still trustworthy; the log is just no longer guaranteed complete.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables
             WHERE schemaname = 'public' AND tablename = 'audit_events') THEN
    REVOKE INSERT, UPDATE ON audit_events FROM authenticated;
  ELSE
    RAISE NOTICE 'audit_events missing — run audit-events.sql first.';
  END IF;
END $$;


-- ---------------------------------------------------------------------------
-- 4. VERIFY — READ-ONLY.
-- ---------------------------------------------------------------------------

-- 4a. Every FK into a parent table and what it now does on delete.
--     Expect 'CASCADE' everywhere except the five SET NULL exceptions.
SELECT src.relname  AS child_table,
       att.attname  AS child_column,
       tgt.relname  AS parent_table,
       CASE con.confdeltype
         WHEN 'c' THEN 'CASCADE' WHEN 'n' THEN 'SET NULL'
         WHEN 'd' THEN 'SET DEFAULT' WHEN 'r' THEN 'RESTRICT'
         ELSE 'NO ACTION' END AS on_delete
FROM pg_constraint con
JOIN pg_class     src ON src.oid = con.conrelid
JOIN pg_class     tgt ON tgt.oid = con.confrelid
JOIN pg_namespace ns  ON ns.oid  = src.relnamespace
JOIN pg_attribute att ON att.attrelid = con.conrelid AND att.attnum = con.conkey[1]
WHERE con.contype = 'f' AND ns.nspname = 'public'
  AND tgt.relname IN ('properties','apartments','issues','inspections',
                      'projects','property_objects','logbook_entries')
ORDER BY 3, 1, 2;

-- 4b. The DELETE policies.
SELECT tablename, policyname, qual
FROM pg_policies
WHERE schemaname = 'public' AND cmd = 'DELETE'
ORDER BY tablename;

-- 4c. Tables that still have RLS on but NO delete policy — anything listed
--     here will silently delete zero rows from the client.
SELECT c.relname AS table_without_delete_policy
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'public' AND c.relkind = 'r' AND c.relrowsecurity
  AND c.relname IN ('properties','apartments','issues','inspections','projects',
                    'logbook_entries','logbook_comments','property_objects',
                    'documents','property_history','audit_events')
  AND NOT EXISTS (
    SELECT 1 FROM pg_policies p
    WHERE p.schemaname = 'public' AND p.tablename = c.relname AND p.cmd = 'DELETE')
ORDER BY 1;


-- ---------------------------------------------------------------------------
-- 5. NOT HANDLED HERE — Supabase Storage.
--
--    documents, issue_images and project_images hold paths into Storage
--    buckets. Cascading the rows deletes the pointers, not the files, so the
--    bucket keeps orphaned objects. Nothing breaks, but storage grows.
--    Reclaiming it needs a Storage-side sweep (or a delete hook on those
--    tables) and is out of scope for this change.
-- ---------------------------------------------------------------------------