/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyrelseRouteImport } from './routes/styrelse'
import { Route as StartRouteImport } from './routes/start'
import { Route as MinaArendenRouteImport } from './routes/mina-arenden'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FelanmalanRouteImport } from './routes/felanmalan'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as BoendeRouteImport } from './routes/boende'
import { Route as ArendestatusRouteImport } from './routes/arendestatus'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOppnaArendenRouteImport } from './routes/_authenticated.oppna-arenden'
import { Route as AuthenticatedLoggbokRouteImport } from './routes/_authenticated.loggbok'
import { Route as AuthenticatedInstallningarRouteImport } from './routes/_authenticated.installningar'
import { Route as AuthenticatedFelanmalningarRouteImport } from './routes/_authenticated.felanmalningar'
import { Route as AuthenticatedEntreprenorerRouteImport } from './routes/_authenticated.entreprenorer'
import { Route as AuthenticatedEkonomiRouteImport } from './routes/_authenticated.ekonomi'
import { Route as AuthenticatedDokumentRouteImport } from './routes/_authenticated.dokument'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedDagRapportRouteImport } from './routes/_authenticated.dag-rapport'
import { Route as AuthenticatedChattRouteImport } from './routes/_authenticated.chatt'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated.projects.index'
import { Route as AuthenticatedObjectsIndexRouteImport } from './routes/_authenticated.objects.index'
import { Route as AuthenticatedIssuesIndexRouteImport } from './routes/_authenticated.issues.index'
import { Route as AuthenticatedInspectionsIndexRouteImport } from './routes/_authenticated.inspections.index'
import { Route as AuthenticatedFastigheterIndexRouteImport } from './routes/_authenticated.fastigheter.index'
import { Route as AuthenticatedContactsIndexRouteImport } from './routes/_authenticated.contacts.index'
import { Route as AuthenticatedApartmentsIndexRouteImport } from './routes/_authenticated.apartments.index'
import { Route as AuthenticatedPropertiesNewRouteImport } from './routes/_authenticated.properties.new'
import { Route as AuthenticatedPropertiesIdRouteImport } from './routes/_authenticated.properties.$id'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated.projects.new'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated.projects.$id'
import { Route as AuthenticatedIssuesNewRouteImport } from './routes/_authenticated.issues.new'
import { Route as AuthenticatedIssuesIdRouteImport } from './routes/_authenticated.issues.$id'
import { Route as AuthenticatedInspectionsNewRouteImport } from './routes/_authenticated.inspections.new'
import { Route as AuthenticatedInspectionsIdRouteImport } from './routes/_authenticated.inspections.$id'
import { Route as AuthenticatedContactsNewRouteImport } from './routes/_authenticated.contacts.new'
import { Route as AuthenticatedContactsIdRouteImport } from './routes/_authenticated.contacts.$id'
import { Route as AuthenticatedApartmentsNewRouteImport } from './routes/_authenticated.apartments.new'
import { Route as AuthenticatedApartmentsIdRouteImport } from './routes/_authenticated.apartments.$id'
import { Route as AuthenticatedPropertiesIdIndexRouteImport } from './routes/_authenticated.properties.$id.index'
import { Route as AuthenticatedFastigheterIdIndexRouteImport } from './routes/_authenticated.fastigheter.$id.index'
import { Route as AuthenticatedPropertiesIdLogbookRouteImport } from './routes/_authenticated.properties.$id.logbook'
import { Route as AuthenticatedPropertiesIdDocumentsRouteImport } from './routes/_authenticated.properties.$id.documents'
import { Route as AuthenticatedPropertiesIdContactsRouteImport } from './routes/_authenticated.properties.$id.contacts'
import { Route as AuthenticatedPropertiesIdAvslutatRouteImport } from './routes/_authenticated.properties.$id.avslutat'
import { Route as AuthenticatedFastigheterIdInstallningarRouteImport } from './routes/_authenticated.fastigheter.$id.installningar'
import { Route as AuthenticatedFastigheterIdDashboardRouteImport } from './routes/_authenticated.fastigheter.$id.dashboard'
import { Route as AuthenticatedPropertiesIdProjectsIndexRouteImport } from './routes/_authenticated.properties.$id.projects.index'
import { Route as AuthenticatedPropertiesIdObjectsIndexRouteImport } from './routes/_authenticated.properties.$id.objects.index'
import { Route as AuthenticatedPropertiesIdIssuesIndexRouteImport } from './routes/_authenticated.properties.$id.issues.index'
import { Route as AuthenticatedPropertiesIdInspectionsIndexRouteImport } from './routes/_authenticated.properties.$id.inspections.index'
import { Route as AuthenticatedPropertiesIdApartmentsIndexRouteImport } from './routes/_authenticated.properties.$id.apartments.index'
import { Route as AuthenticatedPropertiesIdActionsIndexRouteImport } from './routes/_authenticated.properties.$id.actions.index'
import { Route as AuthenticatedPropertiesIdProjectsNewRouteImport } from './routes/_authenticated.properties.$id.projects.new'
import { Route as AuthenticatedPropertiesIdProjectsProjectIdRouteImport } from './routes/_authenticated.properties.$id.projects.$projectId'
import { Route as AuthenticatedPropertiesIdObjectsNewRouteImport } from './routes/_authenticated.properties.$id.objects.new'
import { Route as AuthenticatedPropertiesIdObjectsObjectIdRouteImport } from './routes/_authenticated.properties.$id.objects.$objectId'
import { Route as AuthenticatedPropertiesIdIssuesNewRouteImport } from './routes/_authenticated.properties.$id.issues.new'
import { Route as AuthenticatedPropertiesIdIssuesIssueIdRouteImport } from './routes/_authenticated.properties.$id.issues.$issueId'
import { Route as AuthenticatedPropertiesIdInspectionsNewRouteImport } from './routes/_authenticated.properties.$id.inspections.new'
import { Route as AuthenticatedPropertiesIdInspectionsInspectionIdRouteImport } from './routes/_authenticated.properties.$id.inspections.$inspectionId'
import { Route as AuthenticatedPropertiesIdApartmentsApartmentIdRouteImport } from './routes/_authenticated.properties.$id.apartments.$apartmentId'
import { Route as AuthenticatedPropertiesIdActionsActionIdRouteImport } from './routes/_authenticated.properties.$id.actions.$actionId'

const StyrelseRoute = StyrelseRouteImport.update({
  id: '/styrelse',
  path: '/styrelse',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const MinaArendenRoute = MinaArendenRouteImport.update({
  id: '/mina-arenden',
  path: '/mina-arenden',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FelanmalanRoute = FelanmalanRouteImport.update({
  id: '/felanmalan',
  path: '/felanmalan',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BoendeRoute = BoendeRouteImport.update({
  id: '/boende',
  path: '/boende',
  getParentRoute: () => rootRouteImport,
} as any)
const ArendestatusRoute = ArendestatusRouteImport.update({
  id: '/arendestatus',
  path: '/arendestatus',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOppnaArendenRoute =
  AuthenticatedOppnaArendenRouteImport.update({
    id: '/oppna-arenden',
    path: '/oppna-arenden',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoggbokRoute = AuthenticatedLoggbokRouteImport.update({
  id: '/loggbok',
  path: '/loggbok',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstallningarRoute =
  AuthenticatedInstallningarRouteImport.update({
    id: '/installningar',
    path: '/installningar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFelanmalningarRoute =
  AuthenticatedFelanmalningarRouteImport.update({
    id: '/felanmalningar',
    path: '/felanmalningar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEntreprenorerRoute =
  AuthenticatedEntreprenorerRouteImport.update({
    id: '/entreprenorer',
    path: '/entreprenorer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEkonomiRoute = AuthenticatedEkonomiRouteImport.update({
  id: '/ekonomi',
  path: '/ekonomi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDokumentRoute = AuthenticatedDokumentRouteImport.update({
  id: '/dokument',
  path: '/dokument',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDagRapportRoute = AuthenticatedDagRapportRouteImport.update({
  id: '/dag-rapport',
  path: '/dag-rapport',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChattRoute = AuthenticatedChattRouteImport.update({
  id: '/chatt',
  path: '/chatt',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedObjectsIndexRoute =
  AuthenticatedObjectsIndexRouteImport.update({
    id: '/objects/',
    path: '/objects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIssuesIndexRoute =
  AuthenticatedIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInspectionsIndexRoute =
  AuthenticatedInspectionsIndexRouteImport.update({
    id: '/inspections/',
    path: '/inspections/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFastigheterIndexRoute =
  AuthenticatedFastigheterIndexRouteImport.update({
    id: '/fastigheter/',
    path: '/fastigheter/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContactsIndexRoute =
  AuthenticatedContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApartmentsIndexRoute =
  AuthenticatedApartmentsIndexRouteImport.update({
    id: '/apartments/',
    path: '/apartments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropertiesNewRoute =
  AuthenticatedPropertiesNewRouteImport.update({
    id: '/properties/new',
    path: '/properties/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropertiesIdRoute =
  AuthenticatedPropertiesIdRouteImport.update({
    id: '/properties/$id',
    path: '/properties/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIssuesNewRoute = AuthenticatedIssuesNewRouteImport.update({
  id: '/issues/new',
  path: '/issues/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIssuesIdRoute = AuthenticatedIssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInspectionsNewRoute =
  AuthenticatedInspectionsNewRouteImport.update({
    id: '/inspections/new',
    path: '/inspections/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInspectionsIdRoute =
  AuthenticatedInspectionsIdRouteImport.update({
    id: '/inspections/$id',
    path: '/inspections/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContactsNewRoute =
  AuthenticatedContactsNewRouteImport.update({
    id: '/contacts/new',
    path: '/contacts/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContactsIdRoute = AuthenticatedContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApartmentsNewRoute =
  AuthenticatedApartmentsNewRouteImport.update({
    id: '/apartments/new',
    path: '/apartments/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApartmentsIdRoute =
  AuthenticatedApartmentsIdRouteImport.update({
    id: '/apartments/$id',
    path: '/apartments/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropertiesIdIndexRoute =
  AuthenticatedPropertiesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedFastigheterIdIndexRoute =
  AuthenticatedFastigheterIdIndexRouteImport.update({
    id: '/fastigheter/$id/',
    path: '/fastigheter/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropertiesIdLogbookRoute =
  AuthenticatedPropertiesIdLogbookRouteImport.update({
    id: '/logbook',
    path: '/logbook',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdDocumentsRoute =
  AuthenticatedPropertiesIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdContactsRoute =
  AuthenticatedPropertiesIdContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdAvslutatRoute =
  AuthenticatedPropertiesIdAvslutatRouteImport.update({
    id: '/avslutat',
    path: '/avslutat',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedFastigheterIdInstallningarRoute =
  AuthenticatedFastigheterIdInstallningarRouteImport.update({
    id: '/fastigheter/$id/installningar',
    path: '/fastigheter/$id/installningar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFastigheterIdDashboardRoute =
  AuthenticatedFastigheterIdDashboardRouteImport.update({
    id: '/fastigheter/$id/dashboard',
    path: '/fastigheter/$id/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropertiesIdProjectsIndexRoute =
  AuthenticatedPropertiesIdProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdObjectsIndexRoute =
  AuthenticatedPropertiesIdObjectsIndexRouteImport.update({
    id: '/objects/',
    path: '/objects/',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdIssuesIndexRoute =
  AuthenticatedPropertiesIdIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdInspectionsIndexRoute =
  AuthenticatedPropertiesIdInspectionsIndexRouteImport.update({
    id: '/inspections/',
    path: '/inspections/',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdApartmentsIndexRoute =
  AuthenticatedPropertiesIdApartmentsIndexRouteImport.update({
    id: '/apartments/',
    path: '/apartments/',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdActionsIndexRoute =
  AuthenticatedPropertiesIdActionsIndexRouteImport.update({
    id: '/actions/',
    path: '/actions/',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdProjectsNewRoute =
  AuthenticatedPropertiesIdProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdProjectsProjectIdRoute =
  AuthenticatedPropertiesIdProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdObjectsNewRoute =
  AuthenticatedPropertiesIdObjectsNewRouteImport.update({
    id: '/objects/new',
    path: '/objects/new',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdObjectsObjectIdRoute =
  AuthenticatedPropertiesIdObjectsObjectIdRouteImport.update({
    id: '/objects/$objectId',
    path: '/objects/$objectId',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdIssuesNewRoute =
  AuthenticatedPropertiesIdIssuesNewRouteImport.update({
    id: '/issues/new',
    path: '/issues/new',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdIssuesIssueIdRoute =
  AuthenticatedPropertiesIdIssuesIssueIdRouteImport.update({
    id: '/issues/$issueId',
    path: '/issues/$issueId',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdInspectionsNewRoute =
  AuthenticatedPropertiesIdInspectionsNewRouteImport.update({
    id: '/inspections/new',
    path: '/inspections/new',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdInspectionsInspectionIdRoute =
  AuthenticatedPropertiesIdInspectionsInspectionIdRouteImport.update({
    id: '/inspections/$inspectionId',
    path: '/inspections/$inspectionId',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdApartmentsApartmentIdRoute =
  AuthenticatedPropertiesIdApartmentsApartmentIdRouteImport.update({
    id: '/apartments/$apartmentId',
    path: '/apartments/$apartmentId',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)
const AuthenticatedPropertiesIdActionsActionIdRoute =
  AuthenticatedPropertiesIdActionsActionIdRouteImport.update({
    id: '/actions/$actionId',
    path: '/actions/$actionId',
    getParentRoute: () => AuthenticatedPropertiesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/arendestatus': typeof ArendestatusRoute
  '/boende': typeof BoendeRoute
  '/demo': typeof DemoRoute
  '/felanmalan': typeof FelanmalanRoute
  '/login': typeof LoginRoute
  '/mina-arenden': typeof MinaArendenRoute
  '/start': typeof StartRoute
  '/styrelse': typeof StyrelseRoute
  '/chatt': typeof AuthenticatedChattRoute
  '/dag-rapport': typeof AuthenticatedDagRapportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dokument': typeof AuthenticatedDokumentRoute
  '/ekonomi': typeof AuthenticatedEkonomiRoute
  '/entreprenorer': typeof AuthenticatedEntreprenorerRoute
  '/felanmalningar': typeof AuthenticatedFelanmalningarRoute
  '/installningar': typeof AuthenticatedInstallningarRoute
  '/loggbok': typeof AuthenticatedLoggbokRoute
  '/oppna-arenden': typeof AuthenticatedOppnaArendenRoute
  '/apartments/$id': typeof AuthenticatedApartmentsIdRoute
  '/apartments/new': typeof AuthenticatedApartmentsNewRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/contacts/new': typeof AuthenticatedContactsNewRoute
  '/inspections/$id': typeof AuthenticatedInspectionsIdRoute
  '/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/issues/$id': typeof AuthenticatedIssuesIdRoute
  '/issues/new': typeof AuthenticatedIssuesNewRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/properties/$id': typeof AuthenticatedPropertiesIdRouteWithChildren
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/apartments/': typeof AuthenticatedApartmentsIndexRoute
  '/contacts/': typeof AuthenticatedContactsIndexRoute
  '/fastigheter/': typeof AuthenticatedFastigheterIndexRoute
  '/inspections/': typeof AuthenticatedInspectionsIndexRoute
  '/issues/': typeof AuthenticatedIssuesIndexRoute
  '/objects/': typeof AuthenticatedObjectsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/fastigheter/$id/dashboard': typeof AuthenticatedFastigheterIdDashboardRoute
  '/fastigheter/$id/installningar': typeof AuthenticatedFastigheterIdInstallningarRoute
  '/properties/$id/avslutat': typeof AuthenticatedPropertiesIdAvslutatRoute
  '/properties/$id/contacts': typeof AuthenticatedPropertiesIdContactsRoute
  '/properties/$id/documents': typeof AuthenticatedPropertiesIdDocumentsRoute
  '/properties/$id/logbook': typeof AuthenticatedPropertiesIdLogbookRoute
  '/fastigheter/$id/': typeof AuthenticatedFastigheterIdIndexRoute
  '/properties/$id/': typeof AuthenticatedPropertiesIdIndexRoute
  '/properties/$id/actions/$actionId': typeof AuthenticatedPropertiesIdActionsActionIdRoute
  '/properties/$id/apartments/$apartmentId': typeof AuthenticatedPropertiesIdApartmentsApartmentIdRoute
  '/properties/$id/inspections/$inspectionId': typeof AuthenticatedPropertiesIdInspectionsInspectionIdRoute
  '/properties/$id/inspections/new': typeof AuthenticatedPropertiesIdInspectionsNewRoute
  '/properties/$id/issues/$issueId': typeof AuthenticatedPropertiesIdIssuesIssueIdRoute
  '/properties/$id/issues/new': typeof AuthenticatedPropertiesIdIssuesNewRoute
  '/properties/$id/objects/$objectId': typeof AuthenticatedPropertiesIdObjectsObjectIdRoute
  '/properties/$id/objects/new': typeof AuthenticatedPropertiesIdObjectsNewRoute
  '/properties/$id/projects/$projectId': typeof AuthenticatedPropertiesIdProjectsProjectIdRoute
  '/properties/$id/projects/new': typeof AuthenticatedPropertiesIdProjectsNewRoute
  '/properties/$id/actions/': typeof AuthenticatedPropertiesIdActionsIndexRoute
  '/properties/$id/apartments/': typeof AuthenticatedPropertiesIdApartmentsIndexRoute
  '/properties/$id/inspections/': typeof AuthenticatedPropertiesIdInspectionsIndexRoute
  '/properties/$id/issues/': typeof AuthenticatedPropertiesIdIssuesIndexRoute
  '/properties/$id/objects/': typeof AuthenticatedPropertiesIdObjectsIndexRoute
  '/properties/$id/projects/': typeof AuthenticatedPropertiesIdProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/arendestatus': typeof ArendestatusRoute
  '/boende': typeof BoendeRoute
  '/demo': typeof DemoRoute
  '/felanmalan': typeof FelanmalanRoute
  '/login': typeof LoginRoute
  '/mina-arenden': typeof MinaArendenRoute
  '/start': typeof StartRoute
  '/styrelse': typeof StyrelseRoute
  '/chatt': typeof AuthenticatedChattRoute
  '/dag-rapport': typeof AuthenticatedDagRapportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dokument': typeof AuthenticatedDokumentRoute
  '/ekonomi': typeof AuthenticatedEkonomiRoute
  '/entreprenorer': typeof AuthenticatedEntreprenorerRoute
  '/felanmalningar': typeof AuthenticatedFelanmalningarRoute
  '/installningar': typeof AuthenticatedInstallningarRoute
  '/loggbok': typeof AuthenticatedLoggbokRoute
  '/oppna-arenden': typeof AuthenticatedOppnaArendenRoute
  '/apartments/$id': typeof AuthenticatedApartmentsIdRoute
  '/apartments/new': typeof AuthenticatedApartmentsNewRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/contacts/new': typeof AuthenticatedContactsNewRoute
  '/inspections/$id': typeof AuthenticatedInspectionsIdRoute
  '/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/issues/$id': typeof AuthenticatedIssuesIdRoute
  '/issues/new': typeof AuthenticatedIssuesNewRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/apartments': typeof AuthenticatedApartmentsIndexRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
  '/fastigheter': typeof AuthenticatedFastigheterIndexRoute
  '/inspections': typeof AuthenticatedInspectionsIndexRoute
  '/issues': typeof AuthenticatedIssuesIndexRoute
  '/objects': typeof AuthenticatedObjectsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/fastigheter/$id/dashboard': typeof AuthenticatedFastigheterIdDashboardRoute
  '/fastigheter/$id/installningar': typeof AuthenticatedFastigheterIdInstallningarRoute
  '/properties/$id/avslutat': typeof AuthenticatedPropertiesIdAvslutatRoute
  '/properties/$id/contacts': typeof AuthenticatedPropertiesIdContactsRoute
  '/properties/$id/documents': typeof AuthenticatedPropertiesIdDocumentsRoute
  '/properties/$id/logbook': typeof AuthenticatedPropertiesIdLogbookRoute
  '/fastigheter/$id': typeof AuthenticatedFastigheterIdIndexRoute
  '/properties/$id': typeof AuthenticatedPropertiesIdIndexRoute
  '/properties/$id/actions/$actionId': typeof AuthenticatedPropertiesIdActionsActionIdRoute
  '/properties/$id/apartments/$apartmentId': typeof AuthenticatedPropertiesIdApartmentsApartmentIdRoute
  '/properties/$id/inspections/$inspectionId': typeof AuthenticatedPropertiesIdInspectionsInspectionIdRoute
  '/properties/$id/inspections/new': typeof AuthenticatedPropertiesIdInspectionsNewRoute
  '/properties/$id/issues/$issueId': typeof AuthenticatedPropertiesIdIssuesIssueIdRoute
  '/properties/$id/issues/new': typeof AuthenticatedPropertiesIdIssuesNewRoute
  '/properties/$id/objects/$objectId': typeof AuthenticatedPropertiesIdObjectsObjectIdRoute
  '/properties/$id/objects/new': typeof AuthenticatedPropertiesIdObjectsNewRoute
  '/properties/$id/projects/$projectId': typeof AuthenticatedPropertiesIdProjectsProjectIdRoute
  '/properties/$id/projects/new': typeof AuthenticatedPropertiesIdProjectsNewRoute
  '/properties/$id/actions': typeof AuthenticatedPropertiesIdActionsIndexRoute
  '/properties/$id/apartments': typeof AuthenticatedPropertiesIdApartmentsIndexRoute
  '/properties/$id/inspections': typeof AuthenticatedPropertiesIdInspectionsIndexRoute
  '/properties/$id/issues': typeof AuthenticatedPropertiesIdIssuesIndexRoute
  '/properties/$id/objects': typeof AuthenticatedPropertiesIdObjectsIndexRoute
  '/properties/$id/projects': typeof AuthenticatedPropertiesIdProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/arendestatus': typeof ArendestatusRoute
  '/boende': typeof BoendeRoute
  '/demo': typeof DemoRoute
  '/felanmalan': typeof FelanmalanRoute
  '/login': typeof LoginRoute
  '/mina-arenden': typeof MinaArendenRoute
  '/start': typeof StartRoute
  '/styrelse': typeof StyrelseRoute
  '/_authenticated/chatt': typeof AuthenticatedChattRoute
  '/_authenticated/dag-rapport': typeof AuthenticatedDagRapportRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dokument': typeof AuthenticatedDokumentRoute
  '/_authenticated/ekonomi': typeof AuthenticatedEkonomiRoute
  '/_authenticated/entreprenorer': typeof AuthenticatedEntreprenorerRoute
  '/_authenticated/felanmalningar': typeof AuthenticatedFelanmalningarRoute
  '/_authenticated/installningar': typeof AuthenticatedInstallningarRoute
  '/_authenticated/loggbok': typeof AuthenticatedLoggbokRoute
  '/_authenticated/oppna-arenden': typeof AuthenticatedOppnaArendenRoute
  '/_authenticated/apartments/$id': typeof AuthenticatedApartmentsIdRoute
  '/_authenticated/apartments/new': typeof AuthenticatedApartmentsNewRoute
  '/_authenticated/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/_authenticated/contacts/new': typeof AuthenticatedContactsNewRoute
  '/_authenticated/inspections/$id': typeof AuthenticatedInspectionsIdRoute
  '/_authenticated/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/_authenticated/issues/$id': typeof AuthenticatedIssuesIdRoute
  '/_authenticated/issues/new': typeof AuthenticatedIssuesNewRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/properties/$id': typeof AuthenticatedPropertiesIdRouteWithChildren
  '/_authenticated/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/_authenticated/apartments/': typeof AuthenticatedApartmentsIndexRoute
  '/_authenticated/contacts/': typeof AuthenticatedContactsIndexRoute
  '/_authenticated/fastigheter/': typeof AuthenticatedFastigheterIndexRoute
  '/_authenticated/inspections/': typeof AuthenticatedInspectionsIndexRoute
  '/_authenticated/issues/': typeof AuthenticatedIssuesIndexRoute
  '/_authenticated/objects/': typeof AuthenticatedObjectsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/fastigheter/$id/dashboard': typeof AuthenticatedFastigheterIdDashboardRoute
  '/_authenticated/fastigheter/$id/installningar': typeof AuthenticatedFastigheterIdInstallningarRoute
  '/_authenticated/properties/$id/avslutat': typeof AuthenticatedPropertiesIdAvslutatRoute
  '/_authenticated/properties/$id/contacts': typeof AuthenticatedPropertiesIdContactsRoute
  '/_authenticated/properties/$id/documents': typeof AuthenticatedPropertiesIdDocumentsRoute
  '/_authenticated/properties/$id/logbook': typeof AuthenticatedPropertiesIdLogbookRoute
  '/_authenticated/fastigheter/$id/': typeof AuthenticatedFastigheterIdIndexRoute
  '/_authenticated/properties/$id/': typeof AuthenticatedPropertiesIdIndexRoute
  '/_authenticated/properties/$id/actions/$actionId': typeof AuthenticatedPropertiesIdActionsActionIdRoute
  '/_authenticated/properties/$id/apartments/$apartmentId': typeof AuthenticatedPropertiesIdApartmentsApartmentIdRoute
  '/_authenticated/properties/$id/inspections/$inspectionId': typeof AuthenticatedPropertiesIdInspectionsInspectionIdRoute
  '/_authenticated/properties/$id/inspections/new': typeof AuthenticatedPropertiesIdInspectionsNewRoute
  '/_authenticated/properties/$id/issues/$issueId': typeof AuthenticatedPropertiesIdIssuesIssueIdRoute
  '/_authenticated/properties/$id/issues/new': typeof AuthenticatedPropertiesIdIssuesNewRoute
  '/_authenticated/properties/$id/objects/$objectId': typeof AuthenticatedPropertiesIdObjectsObjectIdRoute
  '/_authenticated/properties/$id/objects/new': typeof AuthenticatedPropertiesIdObjectsNewRoute
  '/_authenticated/properties/$id/projects/$projectId': typeof AuthenticatedPropertiesIdProjectsProjectIdRoute
  '/_authenticated/properties/$id/projects/new': typeof AuthenticatedPropertiesIdProjectsNewRoute
  '/_authenticated/properties/$id/actions/': typeof AuthenticatedPropertiesIdActionsIndexRoute
  '/_authenticated/properties/$id/apartments/': typeof AuthenticatedPropertiesIdApartmentsIndexRoute
  '/_authenticated/properties/$id/inspections/': typeof AuthenticatedPropertiesIdInspectionsIndexRoute
  '/_authenticated/properties/$id/issues/': typeof AuthenticatedPropertiesIdIssuesIndexRoute
  '/_authenticated/properties/$id/objects/': typeof AuthenticatedPropertiesIdObjectsIndexRoute
  '/_authenticated/properties/$id/projects/': typeof AuthenticatedPropertiesIdProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/arendestatus'
    | '/boende'
    | '/demo'
    | '/felanmalan'
    | '/login'
    | '/mina-arenden'
    | '/start'
    | '/styrelse'
    | '/chatt'
    | '/dag-rapport'
    | '/dashboard'
    | '/dokument'
    | '/ekonomi'
    | '/entreprenorer'
    | '/felanmalningar'
    | '/installningar'
    | '/loggbok'
    | '/oppna-arenden'
    | '/apartments/$id'
    | '/apartments/new'
    | '/contacts/$id'
    | '/contacts/new'
    | '/inspections/$id'
    | '/inspections/new'
    | '/issues/$id'
    | '/issues/new'
    | '/projects/$id'
    | '/projects/new'
    | '/properties/$id'
    | '/properties/new'
    | '/apartments/'
    | '/contacts/'
    | '/fastigheter/'
    | '/inspections/'
    | '/issues/'
    | '/objects/'
    | '/projects/'
    | '/fastigheter/$id/dashboard'
    | '/fastigheter/$id/installningar'
    | '/properties/$id/avslutat'
    | '/properties/$id/contacts'
    | '/properties/$id/documents'
    | '/properties/$id/logbook'
    | '/fastigheter/$id/'
    | '/properties/$id/'
    | '/properties/$id/actions/$actionId'
    | '/properties/$id/apartments/$apartmentId'
    | '/properties/$id/inspections/$inspectionId'
    | '/properties/$id/inspections/new'
    | '/properties/$id/issues/$issueId'
    | '/properties/$id/issues/new'
    | '/properties/$id/objects/$objectId'
    | '/properties/$id/objects/new'
    | '/properties/$id/projects/$projectId'
    | '/properties/$id/projects/new'
    | '/properties/$id/actions/'
    | '/properties/$id/apartments/'
    | '/properties/$id/inspections/'
    | '/properties/$id/issues/'
    | '/properties/$id/objects/'
    | '/properties/$id/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/arendestatus'
    | '/boende'
    | '/demo'
    | '/felanmalan'
    | '/login'
    | '/mina-arenden'
    | '/start'
    | '/styrelse'
    | '/chatt'
    | '/dag-rapport'
    | '/dashboard'
    | '/dokument'
    | '/ekonomi'
    | '/entreprenorer'
    | '/felanmalningar'
    | '/installningar'
    | '/loggbok'
    | '/oppna-arenden'
    | '/apartments/$id'
    | '/apartments/new'
    | '/contacts/$id'
    | '/contacts/new'
    | '/inspections/$id'
    | '/inspections/new'
    | '/issues/$id'
    | '/issues/new'
    | '/projects/$id'
    | '/projects/new'
    | '/properties/new'
    | '/apartments'
    | '/contacts'
    | '/fastigheter'
    | '/inspections'
    | '/issues'
    | '/objects'
    | '/projects'
    | '/fastigheter/$id/dashboard'
    | '/fastigheter/$id/installningar'
    | '/properties/$id/avslutat'
    | '/properties/$id/contacts'
    | '/properties/$id/documents'
    | '/properties/$id/logbook'
    | '/fastigheter/$id'
    | '/properties/$id'
    | '/properties/$id/actions/$actionId'
    | '/properties/$id/apartments/$apartmentId'
    | '/properties/$id/inspections/$inspectionId'
    | '/properties/$id/inspections/new'
    | '/properties/$id/issues/$issueId'
    | '/properties/$id/issues/new'
    | '/properties/$id/objects/$objectId'
    | '/properties/$id/objects/new'
    | '/properties/$id/projects/$projectId'
    | '/properties/$id/projects/new'
    | '/properties/$id/actions'
    | '/properties/$id/apartments'
    | '/properties/$id/inspections'
    | '/properties/$id/issues'
    | '/properties/$id/objects'
    | '/properties/$id/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/arendestatus'
    | '/boende'
    | '/demo'
    | '/felanmalan'
    | '/login'
    | '/mina-arenden'
    | '/start'
    | '/styrelse'
    | '/_authenticated/chatt'
    | '/_authenticated/dag-rapport'
    | '/_authenticated/dashboard'
    | '/_authenticated/dokument'
    | '/_authenticated/ekonomi'
    | '/_authenticated/entreprenorer'
    | '/_authenticated/felanmalningar'
    | '/_authenticated/installningar'
    | '/_authenticated/loggbok'
    | '/_authenticated/oppna-arenden'
    | '/_authenticated/apartments/$id'
    | '/_authenticated/apartments/new'
    | '/_authenticated/contacts/$id'
    | '/_authenticated/contacts/new'
    | '/_authenticated/inspections/$id'
    | '/_authenticated/inspections/new'
    | '/_authenticated/issues/$id'
    | '/_authenticated/issues/new'
    | '/_authenticated/projects/$id'
    | '/_authenticated/projects/new'
    | '/_authenticated/properties/$id'
    | '/_authenticated/properties/new'
    | '/_authenticated/apartments/'
    | '/_authenticated/contacts/'
    | '/_authenticated/fastigheter/'
    | '/_authenticated/inspections/'
    | '/_authenticated/issues/'
    | '/_authenticated/objects/'
    | '/_authenticated/projects/'
    | '/_authenticated/fastigheter/$id/dashboard'
    | '/_authenticated/fastigheter/$id/installningar'
    | '/_authenticated/properties/$id/avslutat'
    | '/_authenticated/properties/$id/contacts'
    | '/_authenticated/properties/$id/documents'
    | '/_authenticated/properties/$id/logbook'
    | '/_authenticated/fastigheter/$id/'
    | '/_authenticated/properties/$id/'
    | '/_authenticated/properties/$id/actions/$actionId'
    | '/_authenticated/properties/$id/apartments/$apartmentId'
    | '/_authenticated/properties/$id/inspections/$inspectionId'
    | '/_authenticated/properties/$id/inspections/new'
    | '/_authenticated/properties/$id/issues/$issueId'
    | '/_authenticated/properties/$id/issues/new'
    | '/_authenticated/properties/$id/objects/$objectId'
    | '/_authenticated/properties/$id/objects/new'
    | '/_authenticated/properties/$id/projects/$projectId'
    | '/_authenticated/properties/$id/projects/new'
    | '/_authenticated/properties/$id/actions/'
    | '/_authenticated/properties/$id/apartments/'
    | '/_authenticated/properties/$id/inspections/'
    | '/_authenticated/properties/$id/issues/'
    | '/_authenticated/properties/$id/objects/'
    | '/_authenticated/properties/$id/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ArendestatusRoute: typeof ArendestatusRoute
  BoendeRoute: typeof BoendeRoute
  DemoRoute: typeof DemoRoute
  FelanmalanRoute: typeof FelanmalanRoute
  LoginRoute: typeof LoginRoute
  MinaArendenRoute: typeof MinaArendenRoute
  StartRoute: typeof StartRoute
  StyrelseRoute: typeof StyrelseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/styrelse': {
      id: '/styrelse'
      path: '/styrelse'
      fullPath: '/styrelse'
      preLoaderRoute: typeof StyrelseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mina-arenden': {
      id: '/mina-arenden'
      path: '/mina-arenden'
      fullPath: '/mina-arenden'
      preLoaderRoute: typeof MinaArendenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/felanmalan': {
      id: '/felanmalan'
      path: '/felanmalan'
      fullPath: '/felanmalan'
      preLoaderRoute: typeof FelanmalanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boende': {
      id: '/boende'
      path: '/boende'
      fullPath: '/boende'
      preLoaderRoute: typeof BoendeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arendestatus': {
      id: '/arendestatus'
      path: '/arendestatus'
      fullPath: '/arendestatus'
      preLoaderRoute: typeof ArendestatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/oppna-arenden': {
      id: '/_authenticated/oppna-arenden'
      path: '/oppna-arenden'
      fullPath: '/oppna-arenden'
      preLoaderRoute: typeof AuthenticatedOppnaArendenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loggbok': {
      id: '/_authenticated/loggbok'
      path: '/loggbok'
      fullPath: '/loggbok'
      preLoaderRoute: typeof AuthenticatedLoggbokRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/installningar': {
      id: '/_authenticated/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof AuthenticatedInstallningarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/felanmalningar': {
      id: '/_authenticated/felanmalningar'
      path: '/felanmalningar'
      fullPath: '/felanmalningar'
      preLoaderRoute: typeof AuthenticatedFelanmalningarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entreprenorer': {
      id: '/_authenticated/entreprenorer'
      path: '/entreprenorer'
      fullPath: '/entreprenorer'
      preLoaderRoute: typeof AuthenticatedEntreprenorerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ekonomi': {
      id: '/_authenticated/ekonomi'
      path: '/ekonomi'
      fullPath: '/ekonomi'
      preLoaderRoute: typeof AuthenticatedEkonomiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dokument': {
      id: '/_authenticated/dokument'
      path: '/dokument'
      fullPath: '/dokument'
      preLoaderRoute: typeof AuthenticatedDokumentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dag-rapport': {
      id: '/_authenticated/dag-rapport'
      path: '/dag-rapport'
      fullPath: '/dag-rapport'
      preLoaderRoute: typeof AuthenticatedDagRapportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chatt': {
      id: '/_authenticated/chatt'
      path: '/chatt'
      fullPath: '/chatt'
      preLoaderRoute: typeof AuthenticatedChattRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/objects/': {
      id: '/_authenticated/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof AuthenticatedObjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/issues/': {
      id: '/_authenticated/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof AuthenticatedIssuesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspections/': {
      id: '/_authenticated/inspections/'
      path: '/inspections'
      fullPath: '/inspections/'
      preLoaderRoute: typeof AuthenticatedInspectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fastigheter/': {
      id: '/_authenticated/fastigheter/'
      path: '/fastigheter'
      fullPath: '/fastigheter/'
      preLoaderRoute: typeof AuthenticatedFastigheterIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts/': {
      id: '/_authenticated/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthenticatedContactsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apartments/': {
      id: '/_authenticated/apartments/'
      path: '/apartments'
      fullPath: '/apartments/'
      preLoaderRoute: typeof AuthenticatedApartmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/new': {
      id: '/_authenticated/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof AuthenticatedPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/$id': {
      id: '/_authenticated/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AuthenticatedPropertiesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/issues/new': {
      id: '/_authenticated/issues/new'
      path: '/issues/new'
      fullPath: '/issues/new'
      preLoaderRoute: typeof AuthenticatedIssuesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/issues/$id': {
      id: '/_authenticated/issues/$id'
      path: '/issues/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof AuthenticatedIssuesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspections/new': {
      id: '/_authenticated/inspections/new'
      path: '/inspections/new'
      fullPath: '/inspections/new'
      preLoaderRoute: typeof AuthenticatedInspectionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspections/$id': {
      id: '/_authenticated/inspections/$id'
      path: '/inspections/$id'
      fullPath: '/inspections/$id'
      preLoaderRoute: typeof AuthenticatedInspectionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts/new': {
      id: '/_authenticated/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof AuthenticatedContactsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts/$id': {
      id: '/_authenticated/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AuthenticatedContactsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apartments/new': {
      id: '/_authenticated/apartments/new'
      path: '/apartments/new'
      fullPath: '/apartments/new'
      preLoaderRoute: typeof AuthenticatedApartmentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apartments/$id': {
      id: '/_authenticated/apartments/$id'
      path: '/apartments/$id'
      fullPath: '/apartments/$id'
      preLoaderRoute: typeof AuthenticatedApartmentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/$id/': {
      id: '/_authenticated/properties/$id/'
      path: '/'
      fullPath: '/properties/$id/'
      preLoaderRoute: typeof AuthenticatedPropertiesIdIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/fastigheter/$id/': {
      id: '/_authenticated/fastigheter/$id/'
      path: '/fastigheter/$id'
      fullPath: '/fastigheter/$id/'
      preLoaderRoute: typeof AuthenticatedFastigheterIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/$id/logbook': {
      id: '/_authenticated/properties/$id/logbook'
      path: '/logbook'
      fullPath: '/properties/$id/logbook'
      preLoaderRoute: typeof AuthenticatedPropertiesIdLogbookRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/documents': {
      id: '/_authenticated/properties/$id/documents'
      path: '/documents'
      fullPath: '/properties/$id/documents'
      preLoaderRoute: typeof AuthenticatedPropertiesIdDocumentsRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/contacts': {
      id: '/_authenticated/properties/$id/contacts'
      path: '/contacts'
      fullPath: '/properties/$id/contacts'
      preLoaderRoute: typeof AuthenticatedPropertiesIdContactsRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/avslutat': {
      id: '/_authenticated/properties/$id/avslutat'
      path: '/avslutat'
      fullPath: '/properties/$id/avslutat'
      preLoaderRoute: typeof AuthenticatedPropertiesIdAvslutatRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/fastigheter/$id/installningar': {
      id: '/_authenticated/fastigheter/$id/installningar'
      path: '/fastigheter/$id/installningar'
      fullPath: '/fastigheter/$id/installningar'
      preLoaderRoute: typeof AuthenticatedFastigheterIdInstallningarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fastigheter/$id/dashboard': {
      id: '/_authenticated/fastigheter/$id/dashboard'
      path: '/fastigheter/$id/dashboard'
      fullPath: '/fastigheter/$id/dashboard'
      preLoaderRoute: typeof AuthenticatedFastigheterIdDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/$id/projects/': {
      id: '/_authenticated/properties/$id/projects/'
      path: '/projects'
      fullPath: '/properties/$id/projects/'
      preLoaderRoute: typeof AuthenticatedPropertiesIdProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/objects/': {
      id: '/_authenticated/properties/$id/objects/'
      path: '/objects'
      fullPath: '/properties/$id/objects/'
      preLoaderRoute: typeof AuthenticatedPropertiesIdObjectsIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/issues/': {
      id: '/_authenticated/properties/$id/issues/'
      path: '/issues'
      fullPath: '/properties/$id/issues/'
      preLoaderRoute: typeof AuthenticatedPropertiesIdIssuesIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/inspections/': {
      id: '/_authenticated/properties/$id/inspections/'
      path: '/inspections'
      fullPath: '/properties/$id/inspections/'
      preLoaderRoute: typeof AuthenticatedPropertiesIdInspectionsIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/apartments/': {
      id: '/_authenticated/properties/$id/apartments/'
      path: '/apartments'
      fullPath: '/properties/$id/apartments/'
      preLoaderRoute: typeof AuthenticatedPropertiesIdApartmentsIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/actions/': {
      id: '/_authenticated/properties/$id/actions/'
      path: '/actions'
      fullPath: '/properties/$id/actions/'
      preLoaderRoute: typeof AuthenticatedPropertiesIdActionsIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/projects/new': {
      id: '/_authenticated/properties/$id/projects/new'
      path: '/projects/new'
      fullPath: '/properties/$id/projects/new'
      preLoaderRoute: typeof AuthenticatedPropertiesIdProjectsNewRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/projects/$projectId': {
      id: '/_authenticated/properties/$id/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/properties/$id/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedPropertiesIdProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/objects/new': {
      id: '/_authenticated/properties/$id/objects/new'
      path: '/objects/new'
      fullPath: '/properties/$id/objects/new'
      preLoaderRoute: typeof AuthenticatedPropertiesIdObjectsNewRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/objects/$objectId': {
      id: '/_authenticated/properties/$id/objects/$objectId'
      path: '/objects/$objectId'
      fullPath: '/properties/$id/objects/$objectId'
      preLoaderRoute: typeof AuthenticatedPropertiesIdObjectsObjectIdRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/issues/new': {
      id: '/_authenticated/properties/$id/issues/new'
      path: '/issues/new'
      fullPath: '/properties/$id/issues/new'
      preLoaderRoute: typeof AuthenticatedPropertiesIdIssuesNewRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/issues/$issueId': {
      id: '/_authenticated/properties/$id/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/properties/$id/issues/$issueId'
      preLoaderRoute: typeof AuthenticatedPropertiesIdIssuesIssueIdRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/inspections/new': {
      id: '/_authenticated/properties/$id/inspections/new'
      path: '/inspections/new'
      fullPath: '/properties/$id/inspections/new'
      preLoaderRoute: typeof AuthenticatedPropertiesIdInspectionsNewRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/inspections/$inspectionId': {
      id: '/_authenticated/properties/$id/inspections/$inspectionId'
      path: '/inspections/$inspectionId'
      fullPath: '/properties/$id/inspections/$inspectionId'
      preLoaderRoute: typeof AuthenticatedPropertiesIdInspectionsInspectionIdRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/apartments/$apartmentId': {
      id: '/_authenticated/properties/$id/apartments/$apartmentId'
      path: '/apartments/$apartmentId'
      fullPath: '/properties/$id/apartments/$apartmentId'
      preLoaderRoute: typeof AuthenticatedPropertiesIdApartmentsApartmentIdRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
    '/_authenticated/properties/$id/actions/$actionId': {
      id: '/_authenticated/properties/$id/actions/$actionId'
      path: '/actions/$actionId'
      fullPath: '/properties/$id/actions/$actionId'
      preLoaderRoute: typeof AuthenticatedPropertiesIdActionsActionIdRouteImport
      parentRoute: typeof AuthenticatedPropertiesIdRoute
    }
  }
}

interface AuthenticatedPropertiesIdRouteChildren {
  AuthenticatedPropertiesIdAvslutatRoute: typeof AuthenticatedPropertiesIdAvslutatRoute
  AuthenticatedPropertiesIdContactsRoute: typeof AuthenticatedPropertiesIdContactsRoute
  AuthenticatedPropertiesIdDocumentsRoute: typeof AuthenticatedPropertiesIdDocumentsRoute
  AuthenticatedPropertiesIdLogbookRoute: typeof AuthenticatedPropertiesIdLogbookRoute
  AuthenticatedPropertiesIdIndexRoute: typeof AuthenticatedPropertiesIdIndexRoute
  AuthenticatedPropertiesIdActionsActionIdRoute: typeof AuthenticatedPropertiesIdActionsActionIdRoute
  AuthenticatedPropertiesIdApartmentsApartmentIdRoute: typeof AuthenticatedPropertiesIdApartmentsApartmentIdRoute
  AuthenticatedPropertiesIdInspectionsInspectionIdRoute: typeof AuthenticatedPropertiesIdInspectionsInspectionIdRoute
  AuthenticatedPropertiesIdInspectionsNewRoute: typeof AuthenticatedPropertiesIdInspectionsNewRoute
  AuthenticatedPropertiesIdIssuesIssueIdRoute: typeof AuthenticatedPropertiesIdIssuesIssueIdRoute
  AuthenticatedPropertiesIdIssuesNewRoute: typeof AuthenticatedPropertiesIdIssuesNewRoute
  AuthenticatedPropertiesIdObjectsObjectIdRoute: typeof AuthenticatedPropertiesIdObjectsObjectIdRoute
  AuthenticatedPropertiesIdObjectsNewRoute: typeof AuthenticatedPropertiesIdObjectsNewRoute
  AuthenticatedPropertiesIdProjectsProjectIdRoute: typeof AuthenticatedPropertiesIdProjectsProjectIdRoute
  AuthenticatedPropertiesIdProjectsNewRoute: typeof AuthenticatedPropertiesIdProjectsNewRoute
  AuthenticatedPropertiesIdActionsIndexRoute: typeof AuthenticatedPropertiesIdActionsIndexRoute
  AuthenticatedPropertiesIdApartmentsIndexRoute: typeof AuthenticatedPropertiesIdApartmentsIndexRoute
  AuthenticatedPropertiesIdInspectionsIndexRoute: typeof AuthenticatedPropertiesIdInspectionsIndexRoute
  AuthenticatedPropertiesIdIssuesIndexRoute: typeof AuthenticatedPropertiesIdIssuesIndexRoute
  AuthenticatedPropertiesIdObjectsIndexRoute: typeof AuthenticatedPropertiesIdObjectsIndexRoute
  AuthenticatedPropertiesIdProjectsIndexRoute: typeof AuthenticatedPropertiesIdProjectsIndexRoute
}

const AuthenticatedPropertiesIdRouteChildren: AuthenticatedPropertiesIdRouteChildren =
  {
    AuthenticatedPropertiesIdAvslutatRoute:
      AuthenticatedPropertiesIdAvslutatRoute,
    AuthenticatedPropertiesIdContactsRoute:
      AuthenticatedPropertiesIdContactsRoute,
    AuthenticatedPropertiesIdDocumentsRoute:
      AuthenticatedPropertiesIdDocumentsRoute,
    AuthenticatedPropertiesIdLogbookRoute:
      AuthenticatedPropertiesIdLogbookRoute,
    AuthenticatedPropertiesIdIndexRoute: AuthenticatedPropertiesIdIndexRoute,
    AuthenticatedPropertiesIdActionsActionIdRoute:
      AuthenticatedPropertiesIdActionsActionIdRoute,
    AuthenticatedPropertiesIdApartmentsApartmentIdRoute:
      AuthenticatedPropertiesIdApartmentsApartmentIdRoute,
    AuthenticatedPropertiesIdInspectionsInspectionIdRoute:
      AuthenticatedPropertiesIdInspectionsInspectionIdRoute,
    AuthenticatedPropertiesIdInspectionsNewRoute:
      AuthenticatedPropertiesIdInspectionsNewRoute,
    AuthenticatedPropertiesIdIssuesIssueIdRoute:
      AuthenticatedPropertiesIdIssuesIssueIdRoute,
    AuthenticatedPropertiesIdIssuesNewRoute:
      AuthenticatedPropertiesIdIssuesNewRoute,
    AuthenticatedPropertiesIdObjectsObjectIdRoute:
      AuthenticatedPropertiesIdObjectsObjectIdRoute,
    AuthenticatedPropertiesIdObjectsNewRoute:
      AuthenticatedPropertiesIdObjectsNewRoute,
    AuthenticatedPropertiesIdProjectsProjectIdRoute:
      AuthenticatedPropertiesIdProjectsProjectIdRoute,
    AuthenticatedPropertiesIdProjectsNewRoute:
      AuthenticatedPropertiesIdProjectsNewRoute,
    AuthenticatedPropertiesIdActionsIndexRoute:
      AuthenticatedPropertiesIdActionsIndexRoute,
    AuthenticatedPropertiesIdApartmentsIndexRoute:
      AuthenticatedPropertiesIdApartmentsIndexRoute,
    AuthenticatedPropertiesIdInspectionsIndexRoute:
      AuthenticatedPropertiesIdInspectionsIndexRoute,
    AuthenticatedPropertiesIdIssuesIndexRoute:
      AuthenticatedPropertiesIdIssuesIndexRoute,
    AuthenticatedPropertiesIdObjectsIndexRoute:
      AuthenticatedPropertiesIdObjectsIndexRoute,
    AuthenticatedPropertiesIdProjectsIndexRoute:
      AuthenticatedPropertiesIdProjectsIndexRoute,
  }

const AuthenticatedPropertiesIdRouteWithChildren =
  AuthenticatedPropertiesIdRoute._addFileChildren(
    AuthenticatedPropertiesIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedChattRoute: typeof AuthenticatedChattRoute
  AuthenticatedDagRapportRoute: typeof AuthenticatedDagRapportRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDokumentRoute: typeof AuthenticatedDokumentRoute
  AuthenticatedEkonomiRoute: typeof AuthenticatedEkonomiRoute
  AuthenticatedEntreprenorerRoute: typeof AuthenticatedEntreprenorerRoute
  AuthenticatedFelanmalningarRoute: typeof AuthenticatedFelanmalningarRoute
  AuthenticatedInstallningarRoute: typeof AuthenticatedInstallningarRoute
  AuthenticatedLoggbokRoute: typeof AuthenticatedLoggbokRoute
  AuthenticatedOppnaArendenRoute: typeof AuthenticatedOppnaArendenRoute
  AuthenticatedApartmentsIdRoute: typeof AuthenticatedApartmentsIdRoute
  AuthenticatedApartmentsNewRoute: typeof AuthenticatedApartmentsNewRoute
  AuthenticatedContactsIdRoute: typeof AuthenticatedContactsIdRoute
  AuthenticatedContactsNewRoute: typeof AuthenticatedContactsNewRoute
  AuthenticatedInspectionsIdRoute: typeof AuthenticatedInspectionsIdRoute
  AuthenticatedInspectionsNewRoute: typeof AuthenticatedInspectionsNewRoute
  AuthenticatedIssuesIdRoute: typeof AuthenticatedIssuesIdRoute
  AuthenticatedIssuesNewRoute: typeof AuthenticatedIssuesNewRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedPropertiesIdRoute: typeof AuthenticatedPropertiesIdRouteWithChildren
  AuthenticatedPropertiesNewRoute: typeof AuthenticatedPropertiesNewRoute
  AuthenticatedApartmentsIndexRoute: typeof AuthenticatedApartmentsIndexRoute
  AuthenticatedContactsIndexRoute: typeof AuthenticatedContactsIndexRoute
  AuthenticatedFastigheterIndexRoute: typeof AuthenticatedFastigheterIndexRoute
  AuthenticatedInspectionsIndexRoute: typeof AuthenticatedInspectionsIndexRoute
  AuthenticatedIssuesIndexRoute: typeof AuthenticatedIssuesIndexRoute
  AuthenticatedObjectsIndexRoute: typeof AuthenticatedObjectsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedFastigheterIdDashboardRoute: typeof AuthenticatedFastigheterIdDashboardRoute
  AuthenticatedFastigheterIdInstallningarRoute: typeof AuthenticatedFastigheterIdInstallningarRoute
  AuthenticatedFastigheterIdIndexRoute: typeof AuthenticatedFastigheterIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChattRoute: AuthenticatedChattRoute,
  AuthenticatedDagRapportRoute: AuthenticatedDagRapportRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDokumentRoute: AuthenticatedDokumentRoute,
  AuthenticatedEkonomiRoute: AuthenticatedEkonomiRoute,
  AuthenticatedEntreprenorerRoute: AuthenticatedEntreprenorerRoute,
  AuthenticatedFelanmalningarRoute: AuthenticatedFelanmalningarRoute,
  AuthenticatedInstallningarRoute: AuthenticatedInstallningarRoute,
  AuthenticatedLoggbokRoute: AuthenticatedLoggbokRoute,
  AuthenticatedOppnaArendenRoute: AuthenticatedOppnaArendenRoute,
  AuthenticatedApartmentsIdRoute: AuthenticatedApartmentsIdRoute,
  AuthenticatedApartmentsNewRoute: AuthenticatedApartmentsNewRoute,
  AuthenticatedContactsIdRoute: AuthenticatedContactsIdRoute,
  AuthenticatedContactsNewRoute: AuthenticatedContactsNewRoute,
  AuthenticatedInspectionsIdRoute: AuthenticatedInspectionsIdRoute,
  AuthenticatedInspectionsNewRoute: AuthenticatedInspectionsNewRoute,
  AuthenticatedIssuesIdRoute: AuthenticatedIssuesIdRoute,
  AuthenticatedIssuesNewRoute: AuthenticatedIssuesNewRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedPropertiesIdRoute: AuthenticatedPropertiesIdRouteWithChildren,
  AuthenticatedPropertiesNewRoute: AuthenticatedPropertiesNewRoute,
  AuthenticatedApartmentsIndexRoute: AuthenticatedApartmentsIndexRoute,
  AuthenticatedContactsIndexRoute: AuthenticatedContactsIndexRoute,
  AuthenticatedFastigheterIndexRoute: AuthenticatedFastigheterIndexRoute,
  AuthenticatedInspectionsIndexRoute: AuthenticatedInspectionsIndexRoute,
  AuthenticatedIssuesIndexRoute: AuthenticatedIssuesIndexRoute,
  AuthenticatedObjectsIndexRoute: AuthenticatedObjectsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedFastigheterIdDashboardRoute:
    AuthenticatedFastigheterIdDashboardRoute,
  AuthenticatedFastigheterIdInstallningarRoute:
    AuthenticatedFastigheterIdInstallningarRoute,
  AuthenticatedFastigheterIdIndexRoute: AuthenticatedFastigheterIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ArendestatusRoute: ArendestatusRoute,
  BoendeRoute: BoendeRoute,
  DemoRoute: DemoRoute,
  FelanmalanRoute: FelanmalanRoute,
  LoginRoute: LoginRoute,
  MinaArendenRoute: MinaArendenRoute,
  StartRoute: StartRoute,
  StyrelseRoute: StyrelseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
